query getAllDocsNavGroups {
  groups: allNavGroup {
    title: name
    slug {
      text: current
    }
  }
  pages: allCurriculumApiDocumentationPage {
    title
    slug {
      text: current
    }
    parentGroup: navGroupType {
      slug {
        text: current
      }
    }
  }
}
