query {
  allCurriculumApiLandingPage {
    heroBlock {
      body
      titlePortableTextRaw
      image {
        isPresentational
        asset {
          _id
          url
        }
      }
    }
    content {
      textAndMedia {
        title
        bodyRaw
        image {
          isPresentational
          asset {
            _id
            url
          }
        }
        alignMedia
      }
    }
    usingTheApiSection {
      mainBlock {
        title
        buttonLink {
          external
        }
        image {
          isPresentational
          asset {
            _id
            url
          }
        }
      }
      siblingBlocks {
        title
        buttonLink {
          external
        }
        body
      }
    }
  }
}
