query {
  allCurriculumApiLandingPage(where: { _: { is_draft: false } }) {
    content {
      titleRaw
      bodyRaw
      image {
        asset {
          url
        }
      }
      cta {
        externalLink
        label
        variant
        icon
      }
    }

    usingTheApiSection {
      mainBlock {
        titleRaw
        cta {
          externalLink
          label
          variant
          icon
        }
        image {
          isPresentational
          asset {
            _id
            url
          }
        }
      }
      siblingBlocks {
        titleRaw
        cta {
          externalLink
          label
          variant
          icon
        }
        bodyRaw
      }
    }
  }
}
