query getDocsBySlug($navGroupSlug: String, $docSlug: String) {
  allApiContentPage(
    where: {
      navGroupType: { slug: { current: { eq: $navGroupSlug } } }
      slug: { current: { eq: $docSlug } }
      _: { is_draft: false }
    }
  ) {
    title
    slug {
      text: current
    }
    navGroupType {
      slug {
        text: current
      }
      name
    }
    docsBlocksRaw
  }
}
