name: Run Tests Before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OAK_GRAPHQL_SECRET: ${{ secrets.OAK_GRAPHQL_SECRET }}
      BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
      NEXT_PUBLIC_BUGSNAG_API: ${{ secrets.NEXT_PUBLIC_BUGSNAG_API }}
      OAK_GRAPHQL_HOST: ${{ secrets.OAK_GRAPHQL_HOST }}
      OAK_GRAPHQL_HOST: ${{ secrets.OAK_GRAPHQL_HOST }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      PRISMA_ACCELERATE_DATABASE_URL: ${{ secrets.PRISMA_ACCELERATE_DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
